// The product version lives in more places than anyone remembers. This script
// is the single definition of where, so that bumping and verifying can never
// drift apart — they read the same table below.
//
//   node scripts/bump-version.mjs --check      (= npm run version:check)
//       Assert every site agrees with package.json. Non-zero exit on drift.
//       Cheap and offline: run it in release preflight, before anything is
//       written, so "notes say v1.1.0 but the zip is named v1.2.0" is caught
//       before a minutes-long build rather than after.
//
//   node scripts/bump-version.mjs 1.2.0        (= npm run version:bump -- 1.2.0)
//       Rewrite every site, refresh package-lock, then self-verify with --check.
//
// Not covered on purpose:
//   · The RELEASE_NOTES.md <!-- head: … --> anchor and the prose — the
//     release-pack skill owns those (they need judgement, not substitution).
//   · The VSCode extension's own version (separate cadence). It is READ from
//     packages/vscode-extension/package.json to render the website's version
//     line, never written here.
//   · easymarkdown-intro (a separate repo). The skill reminds you.
//   · Anything derived at build time: __APP_VERSION__ (status bar / welcome),
//     the zip name (pack.mjs), the NSIS artifactName. Those follow package.json.
import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const read = (rel) => readFileSync(resolve(root, rel), 'utf8')
const write = (rel, s) => writeFileSync(resolve(root, rel), s, 'utf8')

const SEMVER = /^\d+\.\d+\.\d+$/

const die = (...lines) => {
  for (const l of lines) console.error(l)
  process.exit(1)
}

// --- inputs -----------------------------------------------------------------
const argv = process.argv.slice(2)
const checkOnly = argv.includes('--check')
const dateArg = argv.find((a) => a.startsWith('--date='))?.slice(7)
const target = argv.find((a) => !a.startsWith('--'))?.replace(/^v/i, '')

if (!checkOnly && !target) {
  die('usage: node scripts/bump-version.mjs <version> [--date=YYYY-MM]',
    '       node scripts/bump-version.mjs --check')
}
if (target && !SEMVER.test(target)) die(`[version] "${target}" 不是 X.Y.Z 形式`)

const current = JSON.parse(read('package.json')).version
const extVersion = JSON.parse(read('packages/vscode-extension/package.json')).version
const ym = dateArg || new Date().toISOString().slice(0, 7)
if (dateArg && !/^\d{4}-\d{2}$/.test(dateArg)) die(`[version] --date 需为 YYYY-MM，收到 "${dateArg}"`)

// --- the table: every place the product version is spelled out ---------------
// Each site exposes `read(text) -> version` and `write(text, v) -> text`.
// A site whose regex stops matching is a hard error, not a silent skip —
// that's how a renamed file or reworded line gets noticed.
const sub = (file, re, build) => ({
  file,
  read: (t) => t.match(re)?.[2],
  write: (t, v) => t.replace(re, (...m) => build(m, v)),
})

const SITES = [
  sub('package.json', /^(\s*"version":\s*")([^"]+)(",)$/m, (m, v) => m[1] + v + m[3]),

  // RELEASE_NOTES: the top section's heading and its first prose line. The
  // hidden head anchor is skill-owned and deliberately untouched.
  sub('RELEASE_NOTES.md', /^(## v)(\d+\.\d+\.\d+)$/m, (m, v) => m[1] + v),
  sub('RELEASE_NOTES.md', /^(EasyMarkdown v)(\d+\.\d+\.\d+)( 更新日志)$/m, (m, v) => m[1] + v + m[3]),

  // Website. index.html's nav/footer strings are the fallback shown when the
  // GitHub releases API yields nothing — which is always, until a v1.* release
  // exists. They are what users actually read, not inert defaults.
  sub('website/index.html', /^(\s*"softwareVersion":\s*")([^"]+)(",)$/m, (m, v) => m[1] + v + m[3]),
  sub('website/index.html', /(id="navVersion">v)(\d+\.\d+\.\d+)(<)/, (m, v) => m[1] + v + m[3]),
  sub('website/index.html', /(id="footVersion">v)(\d+\.\d+\.\d+)(<)/, (m, v) => m[1] + v + m[3]),
  sub('website/index.md', /^(version: v)(\d+\.\d+\.\d+)$/m, (m, v) => m[1] + v),

  // The two llms lines also carry the extension version and a YYYY-MM stamp,
  // so they are rebuilt wholesale rather than patched in place.
  {
    file: 'website/llms.txt',
    read: (t) => t.match(/^- 版本：桌面 v(\d+\.\d+\.\d+)/m)?.[1],
    write: (t, v) =>
      t.replace(/^- 版本：.*$/m, `- 版本：桌面 v${v} · VSCode 扩展 v${extVersion}（${ym}）· 协议：MIT · 价格：免费`),
  },
  {
    file: 'website/llms-full.txt',
    read: (t) => t.match(/^- \*\*版本\*\*：桌面 v(\d+\.\d+\.\d+)/m)?.[1],
    write: (t, v) =>
      t.replace(/^- \*\*版本\*\*：.*$/m,
        `- **版本**：桌面 v${v} · VSCode 扩展 v${extVersion}（${ym}）· **协议**：MIT · **价格**：免费`),
  },
]

// package-lock is regenerated by npm, but still verified — a stale lock makes
// `npm ci` fail with EUSAGE long after the release looks done.
const lockVersions = () => {
  const lock = JSON.parse(read('package-lock.json'))
  return [
    { label: 'package-lock.json (root)', value: lock.version },
    { label: 'package-lock.json (packages[""])', value: lock.packages?.['']?.version },
  ]
}

// --- check ------------------------------------------------------------------
function check(expected) {
  const problems = []
  const seen = []
  for (const site of SITES) {
    const text = read(site.file)
    const found = site.read(text)
    if (found === undefined) {
      problems.push(`${site.file}: 版本行不再匹配 —— 文件被改写过？请更新 scripts/bump-version.mjs 的落点表`)
      continue
    }
    seen.push([site.file, found])
    if (found !== expected) problems.push(`${site.file}: ${found} ≠ ${expected}`)
  }
  for (const { label, value } of lockVersions()) {
    seen.push([label, value])
    if (value !== expected) problems.push(`${label}: ${value} ≠ ${expected}`)
  }

  const width = Math.max(...seen.map(([l]) => l.length))
  for (const [label, v] of seen) {
    const ok = v === expected
    console.log(`  ${ok ? '✓' : '✗'} ${label.padEnd(width)}  ${v}`)
  }
  return problems
}

if (checkOnly) {
  console.log(`[version] package.json = ${current} · VSCode 扩展 = ${extVersion}`)
  const problems = check(current)
  if (problems.length) {
    console.error('\n[version] 版本号不一致：')
    for (const p of problems) console.error('  - ' + p)
    console.error('\n[version] 修复：node scripts/bump-version.mjs ' + current)
    process.exit(1)
  }
  console.log(`\n[version] ${SITES.length + 2} 处全部一致`)
  process.exit(0)
}

// --- bump -------------------------------------------------------------------
// Guard the RELEASE_NOTES rename: the top section must currently be either the
// version we're leaving (incremental — rename it) or the one we're going to
// (the skill already inserted a new section). Anything else means the notes and
// package.json disagree, and blindly renaming would relabel someone else's
// section with this release's number.
const notes = read('RELEASE_NOTES.md')
const topVer = notes.match(/^## v(\d+\.\d+\.\d+)$/m)?.[1]
if (!topVer) die('[version] RELEASE_NOTES.md 里找不到 "## vX.Y.Z" 顶部节')
if (topVer !== current && topVer !== target) {
  die(`[version] RELEASE_NOTES.md 顶部是 v${topVer}，而 package.json 是 ${current}，目标是 ${target}。`,
    '[version] 两者必须先对齐 —— 拒绝改写，否则会把上一个版本的小节挂上新版本号。')
}

console.log(`[version] ${current} → ${target}  (VSCode 扩展 v${extVersion}, 日期 ${ym})`)
for (const site of SITES) {
  const text = read(site.file)
  if (site.read(text) === undefined) {
    die(`[version] ${site.file}: 版本行不再匹配 —— 请更新 scripts/bump-version.mjs 的落点表`)
  }
  write(site.file, site.write(text, target))
}

// npm rewrites both version fields in the lock; it needs no network for this.
// A constant command string, run through the shell: on Windows npm is a .cmd,
// which Node refuses to spawn without one (EINVAL), and execFileSync + shell
// would warn about unescaped args (DEP0190). Nothing here is interpolated, so
// there is no injection surface to escape.
execSync('npm install --package-lock-only --silent', { cwd: root, stdio: 'inherit' })

console.log('')
const problems = check(target)
if (problems.length) {
  console.error('\n[version] 改写后自检失败：')
  for (const p of problems) console.error('  - ' + p)
  process.exit(1)
}
console.log(`\n[version] ${SITES.length + 2} 处全部更新为 ${target}`)
console.log('[version] 仍需手动处理：RELEASE_NOTES.md 的 head 锚点与正文（release-pack skill 负责）、')
console.log('[version] git tag + GitHub Release、以及独立仓库 easymarkdown-intro 的版本号。')
