const STRINGS = {
  zh: {
    appName: 'EasyMarkdown Lite',
    lite: '本地轻量版',
    files: '文件',
    outline: '大纲',
    openFile: '打开文件',
    openFolder: '打开文件夹',
    save: '保存',
    saveAs: '另存为',
    reload: '重新读取',
    undo: '撤销',
    redo: '重做',
    source: '源代码',
    closeSource: '关闭源码',
    close: '关闭',
    searchFiles: '搜索文件',
    noWorkspace: '尚未打开文件夹',
    noFiles: '没有找到 Markdown 文件',
    scanning: '正在读取文件夹…',
    welcomeTitle: '打开本地 Markdown，马上开始',
    welcomeBody: '文档只在当前电脑中读取和保存，不需要安装，也不会上传。',
    welcomeHint: '推荐先打开文件夹，以便显示文件树和相对路径图片。',
    welcomeFileHint: '只处理单个文档时，可直接选择 Markdown 文件。',
    continueFolder: '继续上次的文件夹',
    recentFolder: '上次使用',
    dropHint: '松开以打开 Markdown 文件或文件夹',
    readFailed: '无法读取该文件。请确认浏览器权限后重试。',
    folderFailed: '无法读取该文件夹。请重新授权后重试。',
    writeDenied: '没有取得写入权限。你可以改用“另存为”。',
    saved: '已保存到本地文件',
    downloaded: '浏览器已开始下载文件',
    saveFailed: '保存失败。请检查文件是否被其他程序占用。',
    dirtyClose: '这个文件还有未保存的修改。仍要关闭吗？',
    dirtyReload: '重新读取会丢失未保存的修改。仍要继续吗？',
    externalOverwrite: '文件已被其他程序修改。仍要用当前内容覆盖吗？',
    externalChanged: '磁盘上的文件已有更新',
    reloadNow: '重新读取',
    draftActive: '请先确认或取消当前区块编辑。',
    scanTruncated: '文件数量较多，只显示了前一部分。',
    browserLimited: '当前浏览器不支持直接写回文件，保存时会改为下载。',
    workspaceCount: '{count} 个 Markdown 文件',
    sourceTitle: 'Markdown 源代码',
    applySource: '应用到文档',
    sourceHint: 'Ctrl+Enter 应用修改',
    sourceDirtyClose: '源代码修改尚未应用。仍要关闭吗？',
    noOutline: '当前文档没有标题',
    ready: '本地模式',
    noFileOpen: '未打开文件',
    savedStatus: '已保存',
    modifiedStatus: '未保存',
    filterStatus: '筛选 {shown}/{total} 条',
    filteredTable: '表格 {index}：{shown}/{total} 条',
    clearFilters: '清除全部表格筛选',
    lines: '{count} 行',
    words: '{count} 字符',
    theme: '切换明暗主题',
    typography: '排版',
    typographyTitle: '文档排版',
    typographyIntro: '调整阅读宽度和文字节奏，修改会立即应用到所有已打开文档。',
    typographyStored: '排版设置仅保存在当前浏览器中',
    resetTypography: '恢复默认排版',
    reset: '恢复默认',
    fontSection: '文档字体',
    fontIntro: '可分别设置西文、中文、日文和代码字体。',
    loadFonts: '读取本机字体',
    loadingFonts: '正在读取…',
    fontsLoaded: '已读取 {count} 个本机字体。',
    fontAccessDenied: '浏览器未授予本机字体权限，仍可使用下方常用字体。',
    fontUnsupported: '当前浏览器不支持字体枚举，仍可使用系统默认和常用字体。',
    fontDefault: '系统默认（{name}）',
    fontEnglish: '西文',
    fontChinese: '中文',
    fontJapanese: '日文',
    fontMono: '代码',
    language: '界面语言',
    closeSidebar: '关闭侧边栏',
    showSidebar: '显示侧边栏',
    directFileImages: '从“打开文件夹”进入后，才能解析相对路径图片。',
    linkMissing: '在当前文件夹中找不到链接指向的文档。',
    sourceApplied: '源代码修改已应用',
    permissionCancelled: '未选择文件或权限请求已取消。'
  },
  ja: {
    appName: 'EasyMarkdown Lite',
    lite: 'ローカル軽量版',
    files: 'ファイル',
    outline: 'アウトライン',
    openFile: 'ファイルを開く',
    openFolder: 'フォルダーを開く',
    save: '保存',
    saveAs: '名前を付けて保存',
    reload: '再読み込み',
    undo: '元に戻す',
    redo: 'やり直す',
    source: 'ソース',
    closeSource: 'ソースを閉じる',
    close: '閉じる',
    searchFiles: 'ファイルを検索',
    noWorkspace: 'フォルダーが開かれていません',
    noFiles: 'Markdown ファイルがありません',
    scanning: 'フォルダーを読み込み中…',
    welcomeTitle: 'ローカル Markdown をすぐに編集',
    welcomeBody: '文書はこの端末だけで読み書きされます。インストールもアップロードも不要です。',
    welcomeHint: 'ファイルツリーと相対画像を利用する場合は、フォルダーを開いてください。',
    welcomeFileHint: '1 つの文書だけを扱う場合は、Markdown ファイルを選択します。',
    continueFolder: '前回のフォルダーを開く',
    recentFolder: '前回使用',
    dropHint: 'Markdown ファイルまたはフォルダーをドロップ',
    readFailed: 'ファイルを読み込めません。ブラウザーの権限を確認してください。',
    folderFailed: 'フォルダーを読み込めません。もう一度権限を付与してください。',
    writeDenied: '書き込み権限がありません。「名前を付けて保存」を利用してください。',
    saved: 'ローカルファイルに保存しました',
    downloaded: 'ファイルのダウンロードを開始しました',
    saveFailed: '保存できません。ほかのアプリがファイルを使用していないか確認してください。',
    dirtyClose: '未保存の変更があります。このファイルを閉じますか？',
    dirtyReload: '再読み込みすると未保存の変更が失われます。続行しますか？',
    externalOverwrite: 'ファイルは別のアプリで変更されています。現在の内容で上書きしますか？',
    externalChanged: 'ディスク上のファイルが更新されました',
    reloadNow: '再読み込み',
    draftActive: '編集中のブロックを確定またはキャンセルしてください。',
    scanTruncated: 'ファイル数が多いため、一部だけを表示しています。',
    browserLimited: 'このブラウザーでは直接保存できないため、ダウンロードで保存します。',
    workspaceCount: 'Markdown {count} 件',
    sourceTitle: 'Markdown ソース',
    applySource: '文書へ反映',
    sourceHint: 'Ctrl+Enter で反映',
    sourceDirtyClose: 'ソースの変更がまだ反映されていません。閉じますか？',
    noOutline: 'この文書には見出しがありません',
    ready: 'ローカルモード',
    noFileOpen: 'ファイル未選択',
    savedStatus: '保存済み',
    modifiedStatus: '未保存',
    filterStatus: 'フィルター {shown}/{total} 件',
    filteredTable: '表 {index}：{shown}/{total} 件',
    clearFilters: 'すべての表フィルターを解除',
    lines: '{count} 行',
    words: '{count} 文字',
    theme: 'ライト／ダークを切り替え',
    typography: '組版',
    typographyTitle: '文書の組版',
    typographyIntro: '本文幅と文字のリズムを調整します。変更は開いている文書へ即時反映されます。',
    typographyStored: '組版設定はこのブラウザー内だけに保存されます',
    resetTypography: '組版を初期設定へ戻す',
    reset: '初期設定',
    fontSection: '文書フォント',
    fontIntro: '欧文、中国語、日本語、コードを個別に設定できます。',
    loadFonts: 'ローカルフォントを取得',
    loadingFonts: '取得中…',
    fontsLoaded: 'ローカルフォント {count} 件を取得しました。',
    fontAccessDenied: 'フォント権限が付与されませんでした。標準候補は引き続き利用できます。',
    fontUnsupported:
      'このブラウザーはフォント一覧の取得に対応していません。標準候補を利用できます。',
    fontDefault: 'システム既定（{name}）',
    fontEnglish: '欧文',
    fontChinese: '中国語',
    fontJapanese: '日本語',
    fontMono: 'コード',
    language: '表示言語',
    closeSidebar: 'サイドバーを閉じる',
    showSidebar: 'サイドバーを表示',
    directFileImages: '相対画像は「フォルダーを開く」から開いた場合に表示できます。',
    linkMissing: '現在のフォルダーにリンク先の文書がありません。',
    sourceApplied: 'ソースの変更を反映しました',
    permissionCancelled: 'ファイルが選択されていないか、権限要求がキャンセルされました。'
  },
  en: {
    appName: 'EasyMarkdown Lite',
    lite: 'Local lightweight edition',
    files: 'Files',
    outline: 'Outline',
    openFile: 'Open file',
    openFolder: 'Open folder',
    save: 'Save',
    saveAs: 'Save as',
    reload: 'Reload',
    undo: 'Undo',
    redo: 'Redo',
    source: 'Source',
    closeSource: 'Close source',
    close: 'Close',
    searchFiles: 'Search files',
    noWorkspace: 'No folder is open',
    noFiles: 'No Markdown files found',
    scanning: 'Reading folder…',
    welcomeTitle: 'Open local Markdown and start writing',
    welcomeBody: 'Documents stay on this computer. There is nothing to install or upload.',
    welcomeHint: 'Open a folder to enable the file tree and relative images.',
    welcomeFileHint: 'Choose a Markdown file when you only need one document.',
    continueFolder: 'Continue previous folder',
    recentFolder: 'Previous folder',
    dropHint: 'Drop Markdown files or a folder to open them',
    readFailed: 'The file could not be read. Check browser permissions and try again.',
    folderFailed: 'The folder could not be read. Grant access again and retry.',
    writeDenied: 'Write access was not granted. Try Save as instead.',
    saved: 'Saved to the local file',
    downloaded: 'The browser started downloading the file',
    saveFailed: 'Save failed. Check whether another app is using the file.',
    dirtyClose: 'This file has unsaved changes. Close it anyway?',
    dirtyReload: 'Reloading will discard unsaved changes. Continue?',
    externalOverwrite: 'Another app changed this file. Overwrite it with the current content?',
    externalChanged: 'The file on disk has changed',
    reloadNow: 'Reload',
    draftActive: 'Finish or cancel the current block edit first.',
    scanTruncated: 'This folder is large, so only the first files are shown.',
    browserLimited: 'This browser cannot write files directly. Save will download a copy instead.',
    workspaceCount: '{count} Markdown files',
    sourceTitle: 'Markdown source',
    applySource: 'Apply to document',
    sourceHint: 'Ctrl+Enter to apply',
    sourceDirtyClose: 'Source changes have not been applied. Close anyway?',
    noOutline: 'This document has no headings',
    ready: 'Local mode',
    noFileOpen: 'No file open',
    savedStatus: 'Saved',
    modifiedStatus: 'Unsaved',
    filterStatus: 'Filtered {shown}/{total}',
    filteredTable: 'Table {index}: {shown}/{total}',
    clearFilters: 'Clear all table filters',
    lines: '{count} lines',
    words: '{count} characters',
    theme: 'Toggle light or dark theme',
    typography: 'Typography',
    typographyTitle: 'Document typography',
    typographyIntro:
      'Tune the reading width and text rhythm. Changes apply to every open document.',
    typographyStored: 'Typography settings are stored only in this browser',
    resetTypography: 'Restore default typography',
    reset: 'Reset',
    fontSection: 'Document fonts',
    fontIntro: 'Choose separate fonts for Latin, Chinese, Japanese, and code.',
    loadFonts: 'Load local fonts',
    loadingFonts: 'Loading…',
    fontsLoaded: 'Loaded {count} local fonts.',
    fontAccessDenied: 'Local font access was not granted. The common font choices still work.',
    fontUnsupported:
      'This browser cannot list local fonts. System defaults and common fonts remain available.',
    fontDefault: 'System default ({name})',
    fontEnglish: 'Latin',
    fontChinese: 'Chinese',
    fontJapanese: 'Japanese',
    fontMono: 'Code',
    language: 'Interface language',
    closeSidebar: 'Close sidebar',
    showSidebar: 'Show sidebar',
    directFileImages: 'Open the containing folder to resolve relative images.',
    linkMissing: 'The linked document was not found in the current folder.',
    sourceApplied: 'Source changes applied',
    permissionCancelled: 'No file was selected, or the permission request was cancelled.'
  }
}

export function detectLiteLanguage(value = navigator.language) {
  const normalized = String(value || '').toLowerCase()
  if (normalized.startsWith('ja')) return 'ja'
  if (normalized.startsWith('zh')) return 'zh'
  return 'en'
}

export function liteTranslate(lang, key, vars) {
  let value = STRINGS[lang]?.[key] || STRINGS.en[key] || key
  for (const [name, replacement] of Object.entries(vars || {})) {
    value = value.replaceAll(`{${name}}`, String(replacement))
  }
  return value
}
